In [1]:
import numpy as np
from helper_methods import *


In [4]:
A_s = np.array([[0, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0.5, 0.5, 0.5, 0, 0.5, 0],
                [0, 1, 0, 0, 0, 1, 0, 0],
                [0, 0, 0, 0, 0, 1, 0, 0]], dtype=np.float64)

print(A_s.shape)

(4, 8)


In [14]:

W_z = get_initial_weigA_htA_s()
W_r = get_initial_weighA_st()
W_o = np.random.rand()
U_z = get_initial_weight()
U_r = get_initial_weight()
U_o = np.random.rand()

0.9382719285099876


In [4]:
H = get_initial_weight()

print(H)

[[0.72847483 0.43607576 0.12168063 0.1511067  0.34249914 0.69583378
  0.07910992 0.6003884 ]
 [0.31333506 0.88393803 0.57965652 0.21431353 0.05018971 0.91331666
  0.7081956  0.66675956]
 [0.82268667 0.5722959  0.38329165 0.47717144 0.11000532 0.18493964
  0.10115763 0.19154491]
 [0.61834939 0.82228905 0.63699682 0.3883121  0.13545227 0.24913564
  0.06415658 0.70852753]]


In [5]:
b = np.ones(A_s.shape)

print(b)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


$a_{s, i}$

In [6]:
a_s = np.zeros(A_s.shape)

for i in range(len(A_s)):
    a_s[i] = np.matmul(np.transpose(A_s[i]), H[i]) + b[i]
    

print(a_s.shape)

(4, 8)


In [8]:
z_s = np.ones(A_s.shape)


for i in range(len(a_s)):
    z_s[i] = activation_function_on_vector(sigmoid, (W_z[i] * a_s[i]) + (U_z[i] * A_s[i]))

print(z_s)

[[0.72101836 0.88361372 0.61661013 0.76404502 0.58243191 0.79675142
  0.78801125 0.58148481]
 [0.83354906 0.6635125  0.82362479 0.64763509 0.68710433 0.70914534
  0.85124532 0.72907548]
 [0.6834866  0.77443437 0.81497029 0.68682492 0.57684408 0.69863667
  0.76166931 0.66302222]
 [0.6901783  0.70656119 0.60302404 0.70112155 0.66779731 0.65513454
  0.56191464 0.56821594]]


In [ ]:
r_s = np.ones(A_s.shape)

for i in range(len(a_s)):
    r_s[i] = activation_function_on_vector(sigmoid, (W_r[i] * a_s[i]) + (U_r[i] * A_s[i]))

print(r_s)

In [13]:
v_hidden = np.ones(A_s.shape)

for i in range(len(A_s)):
    v_hidden[i] = activation_function_on_vector(tahn, W_o * )

[[0.46440187 0.31216955]
 [0.74332004 0.25332069]
 [0.49806221 0.98138065]]
[[0.46440187 0.31216955]
 [0.74332004 0.25332069]
 [0.49806221 0.98138065]]
